const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Make a test build take three minutes instead of twenty.
 *
 * ## What was slow, and why
 *
 * `reactNativeArchitectures` defaults to all four ABIs:
 * `armeabi-v7a,arm64-v8a,x86,x86_64`. The New Architecture compiles a
 * substantial amount of C++ per ABI, so that is four full native builds — and
 * for someone testing on a Pixel 7 Pro, three of them are for hardware that
 * will never run the APK. `x86` and `x86_64` exist for emulators;
 * `armeabi-v7a` is 32-bit ARM, which is phones from roughly before 2015.
 *
 * Dropping to `arm64-v8a` alone removes about three quarters of the native
 * work. The daemon and the build cache then make every build after the first
 * incremental, which is the difference between eighteen minutes and three.
 *
 * ## The trade, stated plainly
 *
 * An `arm64-v8a` APK **will not install** on a 32-bit phone or run in a
 * standard Android emulator. That is fine for a development loop on one known
 * handset and wrong for a build handed to testers, so `architectures` is a
 * parameter rather than a constant:
 *
 *     ["./plugins/withFastBuilds", { "architectures": "arm64-v8a" }]          // testing
 *     ["./plugins/withFastBuilds", { "architectures": "armeabi-v7a,arm64-v8a" }]  // distribution
 *
 * Or, without touching this file at all, override it for one build:
 *
 *     ./gradlew assembleRelease -PreactNativeArchitectures=armeabi-v7a,arm64-v8a
 *
 * ## Why a config plugin
 *
 * `/android` is gitignored and regenerated by every `expo prebuild`, so an edit
 * to `android/gradle.properties` survives until the next prebuild and then
 * silently reverts to all four ABIs — and the twenty-minute build comes back
 * looking like a machine problem rather than a setting.
 */
module.exports = function withFastBuilds(config, options = {}) {
  const architectures = options.architectures ?? 'arm64-v8a';
  const parallel = options.parallel !== false;
  const caching = options.caching !== false;

  return withGradleProperties(config, (cfg) => {
    /** Replace the property if the template set one, otherwise append it. */
    const set = (key, value, comment) => {
      const at = cfg.modResults.findIndex(
        (item) => item.type === 'property' && item.key === key
      );
      const entry = { type: 'property', key, value: String(value) };
      if (at === -1) {
        if (comment) cfg.modResults.push({ type: 'comment', value: comment });
        cfg.modResults.push(entry);
      } else {
        cfg.modResults[at] = entry;
      }
    };

    set(
      'reactNativeArchitectures',
      architectures,
      ' Set by plugins/withFastBuilds.js. One ABI is ~4x faster to build; see that file for the trade.'
    );

    if (parallel) {
      set(
        'org.gradle.parallel',
        'true',
        ' Independent modules build at the same time - there are ~40 of them here.'
      );
    }
    if (caching) {
      set(
        'org.gradle.caching',
        'true',
        ' Reuses task outputs across builds, which is most of why a rebuild is minutes not tens of minutes.'
      );
    }

    return cfg;
  });
};
