import { StyleSheet } from 'react-native';
import { colors } from './colors';

// Styles for the shared controls and the redesigned Buy / Sell / Orders /
// Listings screens. Kept apart from styles.ts so the new visual language —
// hairline borders, 12–14 px radii, rose surfaces, maroon for the one thing
// that matters on a surface — lives in one readable place.
export const ui = StyleSheet.create({
  // ---- Select (trigger + bottom sheet) ------------------------------------
  selectTrigger: {
    marginHorizontal: 16, minHeight: 48, borderRadius: 12, borderWidth: 1, borderColor: colors.line,
    backgroundColor: 'white', paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 8,
  },
  selectTriggerCompact: { marginHorizontal: 0, minHeight: 44, paddingHorizontal: 12 },
  selectDisabled: { backgroundColor: '#F7F2F4', opacity: 0.7 },
  selectValue: { flex: 1, color: colors.ink, fontSize: 15, fontWeight: '600' },
  selectPlaceholder: { color: colors.muted, fontWeight: '500' },
  sheet: {
    width: '100%', maxHeight: '78%', backgroundColor: colors.card, borderTopLeftRadius: 22, borderTopRightRadius: 22,
    paddingTop: 8, paddingBottom: 18, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 12,
  },
  sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 4, paddingBottom: 10 },
  sheetTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', flex: 1 },
  sheetSearch: {
    flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, marginBottom: 8, height: 44, borderRadius: 12,
    backgroundColor: colors.cream, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12,
  },
  sheetSearchInput: { flex: 1, color: colors.ink, fontSize: 15, paddingVertical: 0 },
  sheetRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, paddingHorizontal: 20 },
  sheetRowActive: { backgroundColor: colors.rose },
  sheetRowIcon: { fontSize: 20, width: 26, textAlign: 'center' },
  sheetRowText: { flex: 1, color: colors.ink, fontSize: 15.5, fontWeight: '600' },
  sheetRowTextActive: { color: colors.maroon, fontWeight: '800' },
  sheetRowSub: { color: colors.muted, fontSize: 12, marginTop: 1 },
  sheetEmpty: { color: colors.muted, fontSize: 14, textAlign: 'center', paddingVertical: 24 },

  // ---- Skeleton -------------------------------------------------------------
  skel: { backgroundColor: '#EFE4EA', borderRadius: 8 },
  skelCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 10 },
  skelRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  skelGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, paddingHorizontal: 16, marginTop: 12 },
  skelTile: { width: '47.5%', backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, overflow: 'hidden', paddingBottom: 12, gap: 8 },

  // ---- Pills (animal type) and scrolling chips ------------------------------
  pillScroll: { paddingHorizontal: 16, gap: 8, paddingVertical: 2 },
  pill: {
    flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 14, height: 44, borderRadius: 22,
    backgroundColor: 'white', borderWidth: 1.5, borderColor: colors.line,
  },
  pillActive: { backgroundColor: colors.maroon, borderColor: colors.maroon },
  pillIcon: { fontSize: 20 },
  pillText: { color: colors.ink, fontSize: 14.5, fontWeight: '700' },
  pillTextActive: { color: 'white' },
  chip: { paddingHorizontal: 14, height: 38, borderRadius: 19, justifyContent: 'center', backgroundColor: colors.rose, borderWidth: 1, borderColor: 'transparent' },
  chipActive: { backgroundColor: 'white', borderColor: colors.maroon, borderWidth: 1.5 },
  chipText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  chipTextActive: { color: colors.maroon },

  // ---- Section card used by the redesigned forms ---------------------------
  section: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, paddingVertical: 14 },
  sectionTitle: { color: colors.ink, fontSize: 15.5, fontWeight: '800', paddingHorizontal: 14, marginBottom: 2 },
  sectionSub: { color: colors.muted, fontSize: 12, paddingHorizontal: 14, marginBottom: 6, lineHeight: 17 },
  fieldLabel: { color: colors.ink, fontSize: 12.5, fontWeight: '700', paddingHorizontal: 14, marginTop: 12, marginBottom: 6 },
  req: { color: colors.danger },
  row2: { flexDirection: 'row', gap: 10, paddingHorizontal: 14 },
  row2Item: { flex: 1 },
  inputSm: {
    height: 46, borderRadius: 12, borderWidth: 1, borderColor: colors.line, backgroundColor: 'white',
    paddingHorizontal: 12, color: colors.ink, fontSize: 15, fontWeight: '600',
  },

  // ---- Linked live / meat weight --------------------------------------------
  weightLink: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: 14, gap: 6 },
  weightBox: { flex: 1 },
  weightLabel: { color: colors.ink, fontSize: 12.5, fontWeight: '700', marginBottom: 6 },
  weightField: {
    flexDirection: 'row', alignItems: 'center', height: 50, borderRadius: 12, borderWidth: 1.5, borderColor: colors.line,
    backgroundColor: 'white', paddingHorizontal: 12,
  },
  weightFieldFocus: { borderColor: colors.maroon },
  weightInput: { flex: 1, color: colors.ink, fontSize: 19, fontWeight: '800', paddingVertical: 0 },
  weightUnit: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  linkBadge: { alignItems: 'center', justifyContent: 'center', width: 38, height: 50 },
  linkBadgeIcon: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  linkPct: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 2 },
  weightCaption: { color: colors.muted, fontSize: 12, lineHeight: 17, paddingHorizontal: 14, marginTop: 8 },
  textLink: { color: colors.maroon, fontSize: 13.5, fontWeight: '800' },
  measureLink: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, marginTop: 10 },

  // ---- Price breakdown --------------------------------------------------------
  earnBanner: { marginHorizontal: 14, marginTop: 14, borderRadius: 12, backgroundColor: colors.rose, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  earnLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  earnValue: { color: colors.maroon, fontSize: 22, fontWeight: '900' },
  bdCard: { marginHorizontal: 16, marginTop: 12, borderRadius: 14, overflow: 'hidden', backgroundColor: 'white', borderWidth: 1, borderColor: colors.line },
  bdHead: { backgroundColor: colors.maroon, paddingHorizontal: 16, paddingVertical: 12 },
  bdHeadTitle: { color: 'white', fontSize: 17, fontWeight: '800' },
  bdHeadSub: { color: 'rgba(255,255,255,0.82)', fontSize: 12, marginTop: 2 },
  bdRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12, borderTopWidth: 1, borderColor: colors.line },
  bdTitle: { color: colors.ink, fontSize: 14.5, fontWeight: '700' },
  bdSub: { color: colors.muted, fontSize: 12, marginTop: 2, lineHeight: 16 },
  bdRight: { alignItems: 'flex-end', minWidth: 96 },
  bdTotal: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  bdTotalNeg: { color: '#B4443C' },
  bdRate: { color: colors.muted, fontSize: 11.5, marginTop: 2, fontWeight: '600' },
  bdNet: { backgroundColor: '#FBF3F7' },
  bdFinal: { backgroundColor: colors.maroon, paddingHorizontal: 16, paddingVertical: 14 },
  bdFinalLabel: { color: 'rgba(255,255,255,0.85)', fontSize: 13, fontWeight: '700' },
  bdFinalValue: { color: colors.goldPale, fontSize: 26, fontWeight: '900', marginTop: 2 },
  bdFinalSub: { color: 'rgba(255,255,255,0.75)', fontSize: 12, marginTop: 4, lineHeight: 17 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 16, marginTop: 10 },
  tag: { backgroundColor: colors.rose, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 5 },
  tagText: { color: colors.maroon, fontSize: 12.5, fontWeight: '700' },

  // ---- First-purchase offer ---------------------------------------------------
  fpBanner: {
    marginHorizontal: 16, marginTop: 12, borderRadius: 14, backgroundColor: '#FFF7E6', borderWidth: 1, borderColor: '#F6D58E',
    padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12,
  },
  fpIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' },
  fpTitle: { color: '#7A4A06', fontSize: 14.5, fontWeight: '900' },
  fpSub: { color: '#8F6412', fontSize: 12, marginTop: 1 },
  fpRibbon: { position: 'absolute', top: 8, left: 8, backgroundColor: colors.gold, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  fpRibbonText: { color: '#3D2600', fontSize: 10, fontWeight: '900' },

  // ---- Product grid -----------------------------------------------------------
  searchBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, marginTop: 12, height: 46, borderRadius: 14,
    borderWidth: 1, borderColor: colors.line, backgroundColor: 'white', paddingHorizontal: 12,
  },
  searchInput: { flex: 1, color: colors.ink, fontSize: 15, paddingVertical: 0 },
  filterChipRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, marginTop: 10 },
  filterChip: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.maroon, borderRadius: 999, paddingLeft: 12, paddingRight: 8, height: 32 },
  filterChipText: { color: 'white', fontSize: 13, fontWeight: '800' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 16, marginTop: 4 },
  tile: {
    width: '48.2%', marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, overflow: 'hidden',
    shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1,
  },
  tileOff: { opacity: 0.55 },
  tileImage: { width: '100%', aspectRatio: 1.15, backgroundColor: '#F3E9EE' },
  tileImagePh: { width: '100%', aspectRatio: 1.15, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  tileBody: { padding: 10, gap: 3 },
  tileName: { color: colors.ink, fontSize: 14, fontWeight: '800', lineHeight: 19 },
  tilePack: { color: colors.muted, fontSize: 11.5 },
  tilePrice: { color: colors.maroon, fontSize: 17, fontWeight: '900', marginTop: 4 },
  tileUnit: { color: colors.muted, fontSize: 11.5, fontWeight: '600' },
  tileFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
  stockDot: { width: 7, height: 7, borderRadius: 4 },
  stockText: { fontSize: 11, fontWeight: '700' },
  tileWho: { color: colors.muted, fontSize: 11, marginTop: 2 },
  emptyBox: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 24 },
  emptyIcon: { fontSize: 40 },
  emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 8 },
  emptyText: { color: colors.muted, fontSize: 13, textAlign: 'center', marginTop: 4, lineHeight: 19 },

  // ---- Product page -----------------------------------------------------------
  pHero: { marginHorizontal: 16, marginTop: 12, borderRadius: 16, overflow: 'hidden', backgroundColor: 'white', borderWidth: 1, borderColor: colors.line },
  pHeroImage: { width: '100%', aspectRatio: 16 / 10, backgroundColor: colors.line },
  pHeroBody: { padding: 14 },
  pTitle: { color: colors.ink, fontSize: 20, lineHeight: 26, fontWeight: '800', marginTop: 6 },
  pPriceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 6 },
  pPrice: { color: colors.maroon, fontSize: 24, fontWeight: '900' },
  pPriceUnit: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  pPack: { color: colors.muted, fontSize: 12.5, marginLeft: 'auto' },
  pDesc: { color: colors.muted, fontSize: 13.5, lineHeight: 20, marginTop: 8 },
  brandCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, overflow: 'hidden' },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 12 },
  brandRowBorder: { borderTopWidth: 1, borderColor: colors.line },
  brandLogo: { width: 40, height: 40, borderRadius: 10, backgroundColor: 'white', borderWidth: 1, borderColor: colors.line },
  brandLogoPh: { width: 40, height: 40, borderRadius: 10, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  brandKicker: { color: colors.muted, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.3 },
  brandName: { color: colors.ink, fontSize: 14.5, fontWeight: '800', marginTop: 1 },
  brandSub: { color: colors.muted, fontSize: 12, marginTop: 1 },
  scopeNote: { flexDirection: 'row', gap: 8, alignItems: 'flex-start', backgroundColor: '#F2F7FF', paddingHorizontal: 14, paddingVertical: 10, borderTopWidth: 1, borderColor: colors.line },
  scopeText: { flex: 1, color: '#1E3A6E', fontSize: 12.5, lineHeight: 18, fontWeight: '600' },
  factRow: { flexDirection: 'row', gap: 8, marginHorizontal: 16, marginTop: 12 },
  fact: { flex: 1, backgroundColor: 'white', borderRadius: 12, borderWidth: 1, borderColor: colors.line, paddingVertical: 10, paddingHorizontal: 8, alignItems: 'center' },
  factIcon: { fontSize: 18 },
  factValue: { color: colors.ink, fontSize: 12.5, fontWeight: '800', textAlign: 'center', marginTop: 4 },
  factLabel: { color: colors.muted, fontSize: 10.5, textAlign: 'center', marginTop: 1 },
  tabsCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, overflow: 'hidden' },
  tabsBar: { flexDirection: 'row', gap: 6, padding: 6, backgroundColor: '#FAF4F7' },
  tabBtn: { paddingHorizontal: 12, height: 34, borderRadius: 10, justifyContent: 'center' },
  tabBtnActive: { backgroundColor: 'white', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  tabBtnText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  tabBtnTextActive: { color: colors.maroon, fontWeight: '800' },
  tabBody: { paddingHorizontal: 14, paddingVertical: 12 },
  specLine: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 8, borderBottomWidth: 1, borderColor: '#F3E8EE' },
  specKey: { color: colors.muted, fontSize: 13, flex: 1 },
  specVal: { color: colors.ink, fontSize: 13, fontWeight: '700', textAlign: 'right', flexShrink: 1 },
  bodyText: { color: colors.ink, fontSize: 13.5, lineHeight: 21 },
  qtyCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 14 },
  qtyHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  qtyControls: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  qtyBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  qtyValue: { minWidth: 64, alignItems: 'center' },
  qtyNumber: { color: colors.ink, fontSize: 20, fontWeight: '900' },
  qtyUnit: { color: colors.muted, fontSize: 11.5, fontWeight: '700' },
  sumLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5 },
  sumKey: { color: colors.muted, fontSize: 13.5 },
  sumVal: { color: colors.ink, fontSize: 13.5, fontWeight: '700' },
  sumGreen: { color: colors.green, fontWeight: '800' },
  sumTotalKey: { color: colors.ink, fontSize: 15.5, fontWeight: '800' },
  sumTotalVal: { color: colors.maroon, fontSize: 18, fontWeight: '900' },
  divider: { height: 1, backgroundColor: colors.line, marginVertical: 6 },

  // ---- Pinned bottom bar ----------------------------------------------------
  bar: {
    flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: 'white', borderRadius: 16, borderWidth: 1, borderColor: colors.line,
    paddingHorizontal: 14, paddingVertical: 10, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 12, shadowOffset: { width: 0, height: -2 }, elevation: 6,
  },
  barKey: { color: colors.muted, fontSize: 11.5, fontWeight: '700' },
  barTotal: { color: colors.maroon, fontSize: 19, fontWeight: '900' },
  barStrike: { color: colors.muted, fontSize: 11.5, textDecorationLine: 'line-through' },
  barBtn: { flex: 1, height: 48, borderRadius: 12, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  barBtnDisabled: { opacity: 0.45 },
  barBtnText: { color: '#3D2600', fontSize: 15, fontWeight: '900' },

  // ---- Checkout -----------------------------------------------------------------
  lineItem: { flexDirection: 'row', alignItems: 'center', gap: 12, marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 10 },
  lineThumb: { width: 52, height: 52, borderRadius: 10, backgroundColor: colors.rose },
  lineName: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  lineMeta: { color: colors.muted, fontSize: 12, marginTop: 2 },
  lockRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 14, marginTop: 4, borderRadius: 12, backgroundColor: colors.cream, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12, paddingVertical: 11 },
  lockText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '700' },
  lockNote: { color: colors.muted, fontSize: 12, lineHeight: 17, paddingHorizontal: 14, marginTop: 6 },
  payRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 14, marginTop: 4 },
  payChip: { flex: 1, height: 40, borderRadius: 10, borderWidth: 1.5, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', backgroundColor: 'white' },
  payChipActive: { borderColor: colors.maroon, backgroundColor: colors.rose },
  payChipText: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  payChipTextActive: { color: colors.maroon, fontWeight: '800' },
  promoInline: { flexDirection: 'row', gap: 8, paddingHorizontal: 14, marginTop: 4 },
  promoInput: { flex: 1, height: 42, borderRadius: 10, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12, color: colors.ink, fontSize: 14, fontWeight: '800', letterSpacing: 1 },
  promoBtn: { height: 42, paddingHorizontal: 16, borderRadius: 10, backgroundColor: colors.maroon, alignItems: 'center', justifyContent: 'center' },
  promoBtnGhost: { backgroundColor: 'white', borderWidth: 1, borderColor: colors.line },
  promoBtnText: { color: 'white', fontSize: 13.5, fontWeight: '800' },
  promoMsg: { fontSize: 12, lineHeight: 17, paddingHorizontal: 14, marginTop: 6 },
  errorText: { color: colors.danger, fontSize: 12.5, lineHeight: 18, paddingHorizontal: 14, marginTop: 8 },

  // ---- Brand sheet -----------------------------------------------------------------
  brandHead: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 6 },
  brandBigLogo: { width: 84, height: 84, borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: 'white' },
  brandBigName: { color: colors.ink, fontSize: 18, fontWeight: '900', textAlign: 'center', marginTop: 10 },
  brandBigSub: { color: colors.muted, fontSize: 13, textAlign: 'center', marginTop: 2 },
  brandAbout: { color: colors.ink, fontSize: 13.5, lineHeight: 20, marginHorizontal: 20, marginTop: 12 },
  infoLine: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingHorizontal: 20, paddingVertical: 10, borderTopWidth: 1, borderColor: '#F3E8EE' },
  infoText: { flex: 1, color: colors.ink, fontSize: 13.5, lineHeight: 19 },
  infoKey: { color: colors.muted, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.3 },
  sheetBtn: { marginHorizontal: 16, marginTop: 14, height: 48, borderRadius: 12, backgroundColor: colors.maroon, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  sheetBtnText: { color: 'white', fontSize: 15, fontWeight: '800' },

  // ---- Orders & listings --------------------------------------------------------
  oCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 16, borderWidth: 1, borderColor: colors.line, overflow: 'hidden' },
  oTop: { flexDirection: 'row', gap: 12, padding: 12 },
  oThumb: { width: 64, height: 64, borderRadius: 12, backgroundColor: colors.rose },
  oThumbPh: { width: 64, height: 64, borderRadius: 12, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  oTitle: { color: colors.ink, fontSize: 14.5, fontWeight: '800', lineHeight: 20 },
  oMeta: { color: colors.muted, fontSize: 12, marginTop: 3 },
  oCode: { color: colors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 0.3 },
  oFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10, borderTopWidth: 1, borderColor: '#F3E8EE', backgroundColor: '#FCF8FA' },
  oAmount: { color: colors.maroon, fontSize: 17, fontWeight: '900' },
  oLink: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  oLinkText: { color: colors.maroon, fontSize: 13.5, fontWeight: '800' },
  oDiscount: { color: colors.green, fontSize: 12, fontWeight: '700', marginTop: 3 },
  statusPill: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 3, marginTop: 6 },
  statusPillText: { fontSize: 11, fontWeight: '800' },
  miniSteps: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingBottom: 12, gap: 4 },
  miniStep: { flex: 1, height: 5, borderRadius: 3, backgroundColor: '#EFE4EA' },
  miniStepDone: { backgroundColor: colors.green },
  miniStepCurrent: { backgroundColor: '#8B5A2B' },
  dHero: { marginHorizontal: 16, marginTop: 12, borderRadius: 16, backgroundColor: colors.maroon, padding: 16 },
  dHeroKicker: { color: 'rgba(255,255,255,0.75)', fontSize: 11.5, fontWeight: '800', letterSpacing: 0.4 },
  dHeroTitle: { color: 'white', fontSize: 20, fontWeight: '900', marginTop: 4 },
  dHeroSub: { color: 'rgba(255,255,255,0.82)', fontSize: 12.5, marginTop: 4 },
  dHeroRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  dHeroAmount: { color: colors.goldPale, fontSize: 24, fontWeight: '900' },
  dHeroBadge: { backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 999, paddingHorizontal: 11, paddingVertical: 5 },
  dHeroBadgeText: { color: 'white', fontSize: 12, fontWeight: '800' },
  dCard: { marginHorizontal: 16, marginTop: 12, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 14 },
  dCardTitle: { color: colors.ink, fontSize: 15, fontWeight: '800', marginBottom: 8 },
  dItem: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 8 },
  photoStrip: { gap: 8, paddingHorizontal: 16, marginTop: 12 },
  photo: { width: 220, height: 150, borderRadius: 14, backgroundColor: colors.rose },

  // ---- Projects card ----------------------------------------------------------
  projStats: { flexDirection: 'row', marginTop: 12, borderRadius: 12, backgroundColor: '#FBF4F7', borderWidth: 1, borderColor: '#F1E1E9' },
  projStat: { flex: 1, paddingVertical: 10, paddingHorizontal: 6, alignItems: 'center' },
  projStatDivider: { width: 1, backgroundColor: '#EBD9E2', marginVertical: 10 },
  projStatIcon: { fontSize: 16 },
  projStatLabel: { color: colors.muted, fontSize: 10.5, fontWeight: '800', marginTop: 2, textTransform: 'uppercase' },
  projStatValue: { color: colors.ink, fontSize: 12.5, fontWeight: '800', textAlign: 'center', marginTop: 3, lineHeight: 17 },
  partnerStrip: { marginTop: 10, borderRadius: 12, backgroundColor: colors.bluePale, paddingHorizontal: 12, paddingVertical: 10 },
  partnerText: { color: colors.ink, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  partnerLogos: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  partnerX: { color: colors.muted, fontSize: 13, fontWeight: '700' },

  // ---- Market -------------------------------------------------------------------
  mkCard: { marginHorizontal: 16, marginTop: 10, backgroundColor: 'white', borderRadius: 16, borderWidth: 1, borderColor: colors.line, padding: 14 },
  mkRateTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  mkKicker: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  mkRate: { color: colors.maroon, fontSize: 26, fontWeight: '900', marginTop: 2 },
  mkUnit: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  mkSub: { color: colors.ink, fontSize: 12.5, marginTop: 2 },
  scopeChip: { alignSelf: 'flex-start', backgroundColor: '#EEF4FF', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4 },
  scopeChipText: { color: '#1E3A6E', fontSize: 11.5, fontWeight: '700' },
  mkStats: { flexDirection: 'row', marginTop: 12, borderRadius: 12, backgroundColor: '#FBF4F7' },
  mkStat: { flex: 1, alignItems: 'center', paddingVertical: 10 },
  mkStatDivider: { width: 1, backgroundColor: '#EBD9E2', marginVertical: 10 },
  mkStatValue: { color: colors.ink, fontSize: 17, fontWeight: '900' },
  mkStatLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', marginTop: 2, textAlign: 'center' },
  mkFoot: { color: colors.muted, fontSize: 11.5, marginTop: 8 },
  mkGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 16 },
  mkGridCell: { width: '48.5%', marginTop: 10, backgroundColor: 'white', borderRadius: 12, borderWidth: 1, borderColor: colors.line, paddingVertical: 12, alignItems: 'center' },
  upRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginHorizontal: 16, marginTop: 8, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 10 },
  upIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  upTitle: { color: colors.ink, fontSize: 14.5, fontWeight: '800', lineHeight: 20 },
  upMeta: { color: colors.muted, fontSize: 11.5, fontWeight: '600', marginTop: 1 },
  upCard: { marginHorizontal: 16, marginTop: 10, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 12 },
  upCardTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  upThumb: { width: 52, height: 52, borderRadius: 10, backgroundColor: colors.rose },
  upBody: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 8 },
  upFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  rateCard: { marginHorizontal: 16, marginTop: 10, backgroundColor: 'white', borderRadius: 16, borderWidth: 1, borderColor: colors.line, padding: 14 },
  rateHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  rateName: { flex: 1, color: colors.ink, fontSize: 15.5, fontWeight: '800' },
  rateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  rateCell: { width: '48.5%', backgroundColor: colors.cream, borderRadius: 10, paddingVertical: 9, paddingHorizontal: 10 },
  rateCellStrong: { backgroundColor: '#FBF1F6' },
  rateCellLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  rateCellValue: { color: colors.ink, fontSize: 18, fontWeight: '900', marginTop: 2 },
  rateFoot: { color: colors.muted, fontSize: 11.5, marginTop: 8 },

  // ---- Partner strip ------------------------------------------------------------
  partnerRow: { paddingHorizontal: 16, gap: 12, paddingVertical: 4 },
  partnerTile: {
    width: 120, height: 112, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line,
    alignItems: 'center', justifyContent: 'center', padding: 8, gap: 4,
    shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 1,
  },
  partnerTileLogo: { width: 96, height: 50 },
  partnerTileName: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  partnerTileBadge: { backgroundColor: colors.rose, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 1 },
  partnerTileBadgeText: { color: colors.maroon, fontSize: 9.5, fontWeight: '800' },

  // ---- Notifications ------------------------------------------------------------
  bellWrap: { position: 'relative', padding: 2 },
  bellBadge: { position: 'absolute', top: -4, right: -6, minWidth: 17, height: 17, borderRadius: 9, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderWidth: 1.5, borderColor: 'white' },
  bellBadgeText: { color: 'white', fontSize: 9.5, fontWeight: '900' },
  notifCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginHorizontal: 16, marginTop: 10, backgroundColor: 'white', borderRadius: 14, borderWidth: 1, borderColor: colors.line, padding: 12 },
  notifUnread: { borderColor: '#E8C4D4', backgroundColor: '#FFF9FB' },
  notifIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' },
  notifTitle: { color: colors.ink, fontSize: 14.5, fontWeight: '700', lineHeight: 20 },
  notifBody: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 2, opacity: 0.85 },
  notifTime: { color: colors.muted, fontSize: 11.5, marginTop: 4 },
  notifDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.maroon, marginTop: 6 },
});
